## Exercício

Você é um gerente de vendas e tem os dados de vendas de três produtos diferentes (Produto A, Produto B, Produto C) para os últimos 5 dias em um array 2D NumPy. Cada linha do array representa um produto e cada coluna representa um dia. Seu trabalho é calcular as vendas totais para cada produto e para cada dia.

Use o seguinte array para sua análise:

```python
vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])
```

**Solução:**


In [ ]:
import numpy as np

vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])

[325 433 368]


In [ ]:
vendas_produtos = vendas.sum(axis=1)
print(vendas_produtos)

print(f"vendas do produto A: {vendas_produtos[0]}")
print(f"vendas do produto B: {vendas_produtos[1]}")
print(f"vendas do produto C: {vendas_produtos[2]}")

[325 433 368]
vendas do produto A 325
vendas do produto B 433
vendas do produto C 368


In [ ]:
vendas_dia = vendas.sum(axis=0)
print(vendas_dia)

print(f"vendas do dia 1: {vendas_dia[0]}")
print(f"vendas do dia 2: {vendas_dia[1]}")
print(f"vendas do dia 3: {vendas_dia[2]}")
print(f"vendas do dia 4: {vendas_dia[3]}")
print(f"vendas do dia 5: {vendas_dia[4]}")


[207 225 216 234 244]
vendas do dia 1 207
vendas do dia 2 225
vendas do dia 3 216
vendas do dia 4 234
vendas do dia 5 244


In [15]:
dia = 0

for venda in vendas_dia:
    dia += 1
    print(f"Vendas do dia {dia}: {venda}")

Vendas do dia 1: 207
Vendas do dia 2: 225
Vendas do dia 3: 216
Vendas do dia 4: 234
Vendas do dia 5: 244
