## Exercício

Você é um analista de RH e tem os salários de todos os funcionários da sua empresa em um array NumPy. Seu trabalho é identificar quantos funcionários ganham acima da média. Use o seguinte array para sua análise: `salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])`.

In [1]:
import numpy as np

salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])


In [11]:
media_salario = np.mean(salarios)
salario_acima = np.where(salarios > media_salario)

print(salario_acima)
print(salarios[salario_acima])

qtd_acima = np.count_nonzero(salario_acima)
print(qtd_acima)
#Ou
qtd_acima2 = sum(salarios > media_salario)
print(qtd_acima2)




(array([2, 3, 5, 7, 8]),)
[3500 4000 4500 3800 4800]
5
5


In [15]:
rng = np.random.default_rng(seed=23)

salarios_gerados = rng.integers(low=min(salarios), high=max(salarios), size=10, endpoint=True)
print(salarios_gerados)

print(salarios_gerados.min())
print(salarios_gerados.max())
print(salarios_gerados.mean())

[2100 3943 3182 3796 2738 2360 3697 2318 2336 3830]
2100
3943
3030.0
